# index.ps1 -- INDEX.md auto-generation (skill catalog)
#
# Usage:
#   .\scripts\index.ps1
#
# Result: <root>\INDEX.md updated. Do not edit by hand.

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$indexPath = Join-Path $root 'INDEX.md'

$skillDirs = Get-ChildItem -Path $root -Directory | Where-Object {
    Test-Path (Join-Path $_.FullName 'manifest.json')
} | Sort-Object Name

$rows = foreach ($dir in $skillDirs) {
    try {
        $manifest = Get-Content -Raw -Encoding UTF8 (Join-Path $dir.FullName 'manifest.json') | ConvertFrom-Json
    } catch {
        Write-Host "  [skip] $($dir.Name) : invalid manifest.json" -ForegroundColor Yellow
        continue
    }
    [PSCustomObject]@{
        Name    = $manifest.name
        Version = $manifest.version
        Scope   = $manifest.scope
        Purpose = $manifest.purpose
        Folder  = $dir.Name
    }
}

# build markdown
$lines = @()
$lines += "# Skill Index"
$lines += ""
$lines += "_Auto-generated by ``scripts/index.ps1`` from manifest.json files. **Do not edit by hand.**_"
$lines += ""
$lines += "Last generated: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
$lines += "Total: $($rows.Count) skills"
$lines += ""
$lines += "| Skill | Version | Scope | Purpose |"
$lines += "|-------|---------|-------|---------|"

foreach ($row in $rows) {
    $purpose = $row.Purpose -replace '\|', '\|'
    $lines += "| [$($row.Name)]($($row.Folder)/) | $($row.Version) | $($row.Scope) | $purpose |"
}

$lines += ""
$lines += "---"
$lines += ""
$lines += "## Workflow"
$lines += ""
$lines += "| Action | Command |"
$lines += "|--------|---------|"
$lines += "| Validate | ``.\scripts\validate.ps1`` |"
$lines += "| Build / install (global) | ``.\scripts\install.ps1`` |"
$lines += "| Build / install (project) | ``.\scripts\install.ps1 -Target <project>\.claude\skills`` |"
$lines += "| Dry run | ``.\scripts\install.ps1 -DryRun`` |"
$lines += "| Refresh index | ``.\scripts\index.ps1`` (regenerates this file) |"
$lines += ""
$lines += "See [REGISTRY.md](REGISTRY.md) section 6 for the procedure to add a new skill."

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
$content = ($lines -join "`n") + "`n"
[System.IO.File]::WriteAllText($indexPath, $content, $utf8NoBom)

Write-Host "Wrote $indexPath ($($rows.Count) skills)" -ForegroundColor Green
